# Use the official SQL Server 2019 image from Docker Hub
FROM mcr.microsoft.com/mssql/server:2022-latest

# Set environment variables
ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=Un!q@to2023

# Expose the SQL Server port
EXPOSE 1433

# Start SQL Server
CMD ["sqlservr"]
